# Generated by Django 4.2.24 on 2025-09-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client_alter_holding_unique_together_holding_sector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='client_type',
            field=models.CharField(choices=[('individual', 'Individual Investor'), ('wealth_manager', 'Financial Advisor'), ('financial_advisor', 'Financial Advisor'), ('institution', 'Institution')], default='individual', max_length=20),
        ),
    ]
