# Generated by Django 4.2.24 on 2025-09-27 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_userprofile_client_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='wealth_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.wealthmanager'),
        ),
    ]
