# Generated by Django 4.2.24 on 2025-09-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_client_wealth_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvupload',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='csv_uploads/'),
        ),
        migrations.AlterField(
            model_name='csvupload',
            name='file_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
