# Generated by Django 4.2.24 on 2025-09-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_csvupload_file_alter_csvupload_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='sedol',
            field=models.CharField(blank=True, help_text='Stock Exchange Daily Official List', max_length=20, null=True),
        ),
    ]
