# Generated by Django 4.2.24 on 2025-09-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_holding_sedol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='isin',
            field=models.CharField(help_text='International Securities Identification Number', max_length=20),
        ),
    ]
