# Generated by Django 4.2.24 on 2025-09-30 02:44

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_pricesnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="TLHExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_qty", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "original_avg_cost",
                    models.DecimalField(decimal_places=6, max_digits=20),
                ),
                (
                    "original_unrealised_loss",
                    models.DecimalField(decimal_places=6, max_digits=20),
                ),
                (
                    "sell_price",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "sell_fees",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.00"), max_digits=20
                    ),
                ),
                ("sell_date", models.DateField(blank=True, null=True)),
                ("replacement_ticker", models.CharField(blank=True, max_length=20)),
                ("replacement_name", models.CharField(blank=True, max_length=200)),
                (
                    "replacement_qty",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "replacement_price",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "replacement_fees",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.00"), max_digits=20
                    ),
                ),
                ("replacement_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("EXECUTED", "Executed"),
                            ("CANCELLED", "Cancelled"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tlh_executions",
                        to="core.client",
                    ),
                ),
                (
                    "holding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tlh_executions",
                        to="core.holding",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
