# Generated by Django 4.2.24 on 2025-09-30 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_tlhexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='cgtreport',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who generated this report', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
